### ISSUE TITLE
gnl_tester.c - Test 2 count

### ISSUE THREAD

**Issue by victorsempere** [Mazoise/42TESTERS-GNL#2]
The count for test 2 are 9 lines but the after the last \n we find the EOF. We must return 1 in get_next_line? 
If this would be true, the count must be 8 instead of 9.
Sorry if I'm wrong.

**Comment by Mazoise** [comment]
It's 9 because my j variable starts at 1. You should return 8 times 1 and then 0.

**Comment by victorsempere** [comment]
The reason because I get 8 instead of 9 is because when I read the last
line as there is no newline I return 0 so your test doesn't execute the
while that increments j

**Comment by Mazoise** [comment]
You should return 1 each time you get to a \n and then return 0 when you get to EOF and there is no more \n.

**Comment by victorsempere** [comment]
I have detected the problem.
As I Had a problem with the malloc of an empty line and I thought there was
a problem in the test. I commented out the line from a one line while and
then the j=1 was not executed anymore.

Once more your tests. Worked fine.

Thank you so much for your attention. Hopefully I should be helpful for you
at some point.

**Comment by Mazoise** [comment]
Your welcome !
